###############################################################################
# This file contains basic functions: find_dataset_using_name, create_dataset, 
# train_val_split, ... which is used to create the dataset for training
###############################################################################

import importlib
import torch.utils.data
from data.base_dataset import BaseDataset

def find_dataset_using_name(dataset_name):
    dataset_filename = "data." + "dataset_" + dataset_name
    datasetlib = importlib.import_module(dataset_filename)
    dataset = None
    target_dataset_name = dataset_name.replace('_', '') + 'dataset'
    for name, cls in datasetlib.__dict__.items():
        if name.lower() == target_dataset_name.lower() and issubclass(cls, BaseDataset):
            dataset = cls
           
    if dataset is None:
        print("In %s.py, there should be a subclass of BaseDataset with class name that matches %s in lowercase." % (dataset_filename, target_dataset_name))
        exit(0)
    return dataset

def create_dataset(opt):
    dataset = find_dataset_using_name(opt.dataset_mode)
    instance = dataset()
    instance.initialize(opt)
    print("dataset [%s] was created" % (instance.name()))
    return instance

def train_val_split(dataset, val_split=1.0):
    valDataset = torch.utils.data.Subset(dataset, range(0, int(val_split * len(dataset))))
    trainDataset = torch.utils.data.Subset(dataset, range(int(val_split*len(dataset)), len(dataset)))
    return trainDataset, valDataset

class CustomDatasetDataLoader():
    """This class organizes dataset which was generated by 
    create_dataset() function. 
    Note: self.working_subset will be called in train.py to
    evoke the kind of dataset (main, valid) to be used  
    """
        
    def name(self):
        return 'CustomDatasetDataLoader'

    def __init__(self, opt):
        self.opt = opt
        self.working_subset = 'main'
        self.mainDataset, self.validDataset = train_val_split(create_dataset(opt), opt.validDataset_split)
        self.mainDataloader = torch.utils.data.DataLoader(
            self.mainDataset,
            batch_size=opt.batch_size,
            shuffle=not opt.serial_batches,
            num_workers=int(opt.num_threads))
        
        if len(self.validDataset) != 0:
            self.validDataloader = torch.utils.data.DataLoader(
                self.validDataset,
                batch_size=opt.batch_size,
                shuffle=not opt.serial_batches,
                num_workers=int(opt.num_threads))        
        
    def load_data(self):
        return self

    def __len__(self):
        return min(len(getattr(self, self.working_subset + 'Dataset')), self.opt.max_dataset_size)

    def __iter__(self):
        for i, data in enumerate(getattr(self, self.working_subset + 'Dataloader')):
            if i * self.opt.batch_size >= self.opt.max_dataset_size:
                break
            yield data